name: StolpersteineErlangen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.0
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/Stolperstein/Bauer_Amalia/
    - assets/Images/Stolperstein/Bauer_Ernestine/
    - assets/Images/Stolperstein/Bauer_Josef/
    - assets/Images/Stolperstein/Bauer_Simon/
    - assets/Images/Stolperstein/Benesi_Erich/
    - assets/Images/Stolperstein/Benesi_Gottliebe/
    - assets/Images/Stolperstein/Benesi_Hannelore/
    - assets/Images/Stolperstein/Benesi_Hildegard/
    - assets/Images/Stolperstein/Benesi_Jakob/
    - assets/Images/Stolperstein/Cohn_Alfred/
    - assets/Images/Stolperstein/Cohn_Rosa/
    - assets/Images/Stolperstein/Dreifuss_Adolf/
    - assets/Images/Stolperstein/Fleischhauer_Bertha/
    - assets/Images/Stolperstein/Heyer_Gustav/
    - assets/Images/Stolperstein/Katz_Wilma/
    - assets/Images/Stolperstein/Rotenstein_Jenny/
    - assets/Images/Stolperstein/Rotenstein_Simon/
    - assets/Images/Stolperstein/Rotenstein_Sophie/
    - assets/Images/Stolperstein/Uhlfelder_Frieda/
    - assets/Images/Stolperstein/Uhlfelder_Josef/
    - assets/Images/Stolperstein/Vissing_Hildegard/
    - assets/Images/Stolperstein/Wassermann_Thekla/
    - assets/Images/Stolperstein/Weglein_Klothilde/
    - assets/Images/Stolperstein/Weglein_Samuel/
    - assets/Images/Stolperstein/Weinstock_Ivan/
    - assets/Images/Stolperstein/Wild_Ignatz/
    - assets/Images/Stolperstein/Wild_Paula/

    - assets/Audio/Stolperstein/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
